### ISSUE TITLE
can't echo one part of the JSON array in PHP. 

### ISSUE THREAD

**Issue by Benspring100** [JustinHook/royal-mail-price-api#1]
I am trying to output just the singular values such as just the price of compensation of one piece in the array but can;t get it to work.

I tried the approach of doing:

$arr = $calculator->calculatePrice($package);

foreach($arr as $val) {
    echo $val['service'].'<br>';
    echo $val['prices']['price'].'<br>';
    echo $val['prices']['compensation'].'<br>'; 
} 

But simply cannot get it to just output the singular object variables.

How will I just output the price and compensation of a certain service?

**Comment by JustinHook** [comment]
The below code uses https://github.com/JustinHook/royal-mail-price-calculator and not the API. It outputs the three different prices for the `GuaranteedByOnePmService`.

One service can have many prices for one package, each with different compensation.

``` php
<?php

require 'vendor/autoload.php';

use \RoyalMailPriceCalculator\Calculator;
use \RoyalMailPriceCalculator\Package;
use \RoyalMailPriceCalculator\Services\GuaranteedByOnePmService;

$calculator = new Calculator();

$package = new Package();
$package->setDimensions(15, 15, 0.4);
$package->setWeight(90);

$calculator->setServices(array(new GuaranteedByOnePmService()));

$calculated_service_prices = $calculator->calculatePrice($package);


foreach($calculated_service_prices as $calculated_service_price) {
    echo "Service: " . $calculated_service_price['service']->getName() . "\n\n";

     foreach($calculated_service_price['prices'] as $price) {
        echo "Price: " . $price['price'] . "\t";
        echo "Compensation: " . $price['compensation'];
        echo "\n";
     }
}
```

Will output:

```
Service: Guaranteed by 1pm

Price: 6.45 Compensation: 500
Price: 7.45 Compensation: 1000
Price: 9.45 Compensation: 2500
```
